Створення анкети

@startuml
actor Адміністратор as a
control Система as s
 a -> s : Запит на створення анкети
 a <-- s: Пуста анкета
 a -> s : Заповнена анкета
 s -> s : Зберігає анкету
 a <-- s: Повідомляє результат операції
@enduml

Зміна оформлення

@startuml
actor Адміністратор as a
control Система as s
 a -> s : Запит на зміну оформлення
 a <-- s: Варіанти оформлення
 a -> s : Вибирає вид оформлення
 s -> s : Зберігає обраний дизайн
 a <-- s: Повідомляє результат операції
@enduml

Налаштування умов доступу

@startuml
actor Адміністратор as a
control Система as s
 a -> s : Запит на налаштування умов доступу
 a <-- s: Надає право на налаштування
 a -> s : Результати налаштування
 s -> s : Зберігає результати налаштування
 a <-- s: Повідомляє результат операції
@enduml

Додавання запитань в анкету

@startuml
actor Адміністратор as a
control Система as s
 a -> s : Запит на додавання запитання
 a <-- s: Варіанти запитань
 a -> s : Вибирає вид запитання
 s --> a : Пустий шаблон запитання
 a -> s : Заповнений шаблон запитання
 s -> s : Зберігає запитання
 a <-- s: Повідомляє результат операції
@enduml

Видалення анкети

@startuml
actor Адміністратор as a
control Система as s
 a -> s : Знайти анкету
 s -> s : Шукає анкету
 a <-- s: Анкета
 a -> s : Видалити анкету
 s -> s : Видаляє анкету
 a <-- s: Повідомляє результат операції
@enduml

Редагування анкети

@startuml
actor Адміністратор as a
control Система as s
 a -> s : Знайти анкету
 s -> s : Шукає анкету
 a <-- s: Анкета
 a -> s : Редагування анкети
 s -> s : Зберігає зміни
 a <-- s: Повідомляє результат операції
@enduml

Аутентифікація

@startuml
actor Експерт as a
control Система as s
 a -> s : Запит на аутентифікацію
 a <-- s: Форма аутентифікації
 a -> s : Дані для доступу
 s -> s : Перевіряє параметри доступу
 a <-- s: Повідомляє результат операції
@enduml

Заповнення анкети

@startuml
actor Експерт as a
control Система as s
 a -> s : Запит на заповнення анкети
 s -> s : Перевіряє параметри доступу
 a <-- s: Анкета
 a -> s : Заповнена анкета
 s -> s : Зберігає результати опитування
 a <-- s: Повідомляє результат операції
@enduml